//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firstmile.domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FirstMileEntities : DbContext
    {
        public FirstMileEntities()
            : base("name=FirstMileEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FmEquipment> FmEquipments { get; set; }
        public virtual DbSet<FmUser> FmUsers { get; set; }
        public virtual DbSet<FmLookUpType> FmLookUpTypes { get; set; }
        public virtual DbSet<FmProvince> FmProvinces { get; set; }
        public virtual DbSet<FmBookEquipment> FmBookEquipments { get; set; }
        public virtual DbSet<FmBooking> FmBookings { get; set; }
        public virtual DbSet<FmCustomer> FmCustomers { get; set; }
        public virtual DbSet<FmCustomerUser> FmCustomerUsers { get; set; }
        public virtual DbSet<ApiLog> ApiLogs { get; set; }
        public virtual DbSet<FmUsage> FmUsages { get; set; }
        public virtual DbSet<Meili> Meilis { get; set; }
    }
}
