//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firstmile.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FmBooking : BaseEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FmBooking()
        {
            this.FmBookEquipments = new HashSet<FmBookEquipment>();
        }
    
        public int SalesId { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public string ProjectName { get; set; }
        public string Color { get; set; }
        public int StatusId { get; set; }
        public int ServiceTypeId { get; set; }
        public string Comment { get; set; }
        public string ShippingInfo { get; set; }
        public Nullable<System.DateTime> DropOffDate { get; set; }
        public string Discount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FmBookEquipment> FmBookEquipments { get; set; }
        public virtual FmCustomer FmCustomer { get; set; }
    }
}
