//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firstmile.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FmBookEquipment : BaseEntity
    {
        public int SaleEquipmentId { get; set; }
        public int SaleId { get; set; }
        public Nullable<int> EquipmentId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public System.DateTime BorrowedDateFrom { get; set; }
        public System.DateTime BorrowedDateTo { get; set; }
        public int ServiceTypeId { get; set; }
    
        public virtual FmBooking FmBooking { get; set; }
    }
}
