//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firstmile.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FmLookUpType : BaseEntity
    {
        public int LookUpTypeId { get; set; }
        public string EntityCode { get; set; }
        public string Description { get; set; }
        public int LookUpValue { get; set; }
        public int Ordinal { get; set; }
    }
}
