//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firstmile.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meili : BaseEntity
    {
        public int MeiliId { get; set; }
        public int EquipmentId { get; set; }
        public int SubscriptionId { get; set; }
        public int CameraId { get; set; }
        public int FileDestination { get; set; }
        public string ProjectName { get; set; }
        public int EncoderId { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
